name: Build and release Systemd sysext images
on:
  pull_request:

  push:
    tags:
      - 'latest'
      - '[0-9]+'
jobs:
  build:
    runs-on: ubuntu-22.04
    permissions:
      # allow the action to create a release
      contents: write
    steps:
      # checkout the sources
      - uses: actions/checkout@v4
        with:
          path: bakery

      # prepare build host
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: install prerequisites
        run: |
          set -euxo pipefail

          sudo apt update -qq && sudo apt install -yqq \
            curl \
            jq \
            squashfs-tools \
            xz-utils \
            qemu-utils \
            gawk

      - name: build flatcar image
        run: |
          bunzip2 --help
          exit 1
          pushd bakery
          wget https://github.com/flatcar/sysext-bakery/releases/download/latest/kubernetes-v1.27.3-x86-64.raw -o kubernetes.raw
          ./bake_flatcar_image.sh kubernetes:kubernetes.raw --vendor kubevirt
          bunzip2 flatcar_production_kubevirt_image.qcow2.bz2
          # qemu-img convert -f raw -O qcow2 flatcar_production_image.bin flatcar_production_image.qcow2

      # - name: create a new latest release with some artifacts
      #   uses: softprops/action-gh-release@v2
      #   with:
      #     make_latest: true
      #     files: |
      #       bakery/flatcar_production_kubevirt_image.qcow2
